spring.application.name=map-module

spring.cloud.gcp.spanner.project-id=spannerconnection
spring.cloud.gcp.spanner.instance-id=spannercrud
spring.cloud.gcp.spanner.database=demodb
spring.cloud.gcp.credentials.location = classpath:spannerconnection-c9a083a434aa.json

